//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18408.
// 
#pragma warning disable 1591

namespace practica1Cliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="servicioSOAP", Namespace="http://www.example.org/servicio/")]
    public partial class servicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validarNIFOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarIBANOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaCodigoPostalOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarPresupuestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitarPresupuestoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public servicio() {
            this.Url = global::practica1Cliente.Properties.Settings.Default.practica1Cliente_localhost_servicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validarNIFCompletedEventHandler validarNIFCompleted;
        
        /// <remarks/>
        public event validarIBANCompletedEventHandler validarIBANCompleted;
        
        /// <remarks/>
        public event consultaCodigoPostalCompletedEventHandler consultaCodigoPostalCompleted;
        
        /// <remarks/>
        public event generarPresupuestoCompletedEventHandler generarPresupuestoCompleted;
        
        /// <remarks/>
        public event solicitarPresupuestoCompletedEventHandler solicitarPresupuestoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/servicio/validarNIF", RequestNamespace="http://www.example.org/servicio/", ResponseNamespace="http://www.example.org/servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool validarNIF([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nif, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey) {
            object[] results = this.Invoke("validarNIF", new object[] {
                        nif,
                        SoapKey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarNIFAsync(string nif, string SoapKey) {
            this.validarNIFAsync(nif, SoapKey, null);
        }
        
        /// <remarks/>
        public void validarNIFAsync(string nif, string SoapKey, object userState) {
            if ((this.validarNIFOperationCompleted == null)) {
                this.validarNIFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarNIFOperationCompleted);
            }
            this.InvokeAsync("validarNIF", new object[] {
                        nif,
                        SoapKey}, this.validarNIFOperationCompleted, userState);
        }
        
        private void OnvalidarNIFOperationCompleted(object arg) {
            if ((this.validarNIFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarNIFCompleted(this, new validarNIFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/servicio/validarIBAN", RequestNamespace="http://www.example.org/servicio/", ResponseNamespace="http://www.example.org/servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool validarIBAN([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string iban, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string error) {
            object[] results = this.Invoke("validarIBAN", new object[] {
                        iban,
                        SoapKey});
            error = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarIBANAsync(string iban, string SoapKey) {
            this.validarIBANAsync(iban, SoapKey, null);
        }
        
        /// <remarks/>
        public void validarIBANAsync(string iban, string SoapKey, object userState) {
            if ((this.validarIBANOperationCompleted == null)) {
                this.validarIBANOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarIBANOperationCompleted);
            }
            this.InvokeAsync("validarIBAN", new object[] {
                        iban,
                        SoapKey}, this.validarIBANOperationCompleted, userState);
        }
        
        private void OnvalidarIBANOperationCompleted(object arg) {
            if ((this.validarIBANCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarIBANCompleted(this, new validarIBANCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/servicio/consultaCodigoPostal", RequestNamespace="http://www.example.org/servicio/", ResponseNamespace="http://www.example.org/servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("codigoPostal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaCodigoPostal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CodigoPostal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string poblacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string provincia) {
            object[] results = this.Invoke("consultaCodigoPostal", new object[] {
                        CodigoPostal,
                        SoapKey});
            poblacion = ((string)(results[1]));
            provincia = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaCodigoPostalAsync(string CodigoPostal, string SoapKey) {
            this.consultaCodigoPostalAsync(CodigoPostal, SoapKey, null);
        }
        
        /// <remarks/>
        public void consultaCodigoPostalAsync(string CodigoPostal, string SoapKey, object userState) {
            if ((this.consultaCodigoPostalOperationCompleted == null)) {
                this.consultaCodigoPostalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaCodigoPostalOperationCompleted);
            }
            this.InvokeAsync("consultaCodigoPostal", new object[] {
                        CodigoPostal,
                        SoapKey}, this.consultaCodigoPostalOperationCompleted, userState);
        }
        
        private void OnconsultaCodigoPostalOperationCompleted(object arg) {
            if ((this.consultaCodigoPostalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCodigoPostalCompleted(this, new consultaCodigoPostalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/servicio/generarPresupuesto", RequestNamespace="http://www.example.org/servicio/", ResponseNamespace="http://www.example.org/servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("idPresupuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int generarPresupuesto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime fechaPresupuesto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int cantidadProducto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool presupuestoGeneradoCorrectamente) {
            object[] results = this.Invoke("generarPresupuesto", new object[] {
                        fechaPresupuesto,
                        idCliente,
                        referenciaProducto,
                        cantidadProducto,
                        SoapKey});
            presupuestoGeneradoCorrectamente = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void generarPresupuestoAsync(System.DateTime fechaPresupuesto, int idCliente, string referenciaProducto, int cantidadProducto, string SoapKey) {
            this.generarPresupuestoAsync(fechaPresupuesto, idCliente, referenciaProducto, cantidadProducto, SoapKey, null);
        }
        
        /// <remarks/>
        public void generarPresupuestoAsync(System.DateTime fechaPresupuesto, int idCliente, string referenciaProducto, int cantidadProducto, string SoapKey, object userState) {
            if ((this.generarPresupuestoOperationCompleted == null)) {
                this.generarPresupuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarPresupuestoOperationCompleted);
            }
            this.InvokeAsync("generarPresupuesto", new object[] {
                        fechaPresupuesto,
                        idCliente,
                        referenciaProducto,
                        cantidadProducto,
                        SoapKey}, this.generarPresupuestoOperationCompleted, userState);
        }
        
        private void OngenerarPresupuestoOperationCompleted(object arg) {
            if ((this.generarPresupuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarPresupuestoCompleted(this, new generarPresupuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/servicio/solicitarPresupuesto", RequestNamespace="http://www.example.org/servicio/", ResponseNamespace="http://www.example.org/servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("precioPieza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float solicitarPresupuesto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaPieza, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idProveedor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool disponibilidadPieza, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] out System.DateTime fechaDisponibilidadPieza) {
            object[] results = this.Invoke("solicitarPresupuesto", new object[] {
                        referenciaPieza,
                        idProveedor,
                        SoapKey});
            disponibilidadPieza = ((bool)(results[1]));
            fechaDisponibilidadPieza = ((System.DateTime)(results[2]));
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarPresupuestoAsync(string referenciaPieza, int idProveedor, string SoapKey) {
            this.solicitarPresupuestoAsync(referenciaPieza, idProveedor, SoapKey, null);
        }
        
        /// <remarks/>
        public void solicitarPresupuestoAsync(string referenciaPieza, int idProveedor, string SoapKey, object userState) {
            if ((this.solicitarPresupuestoOperationCompleted == null)) {
                this.solicitarPresupuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarPresupuestoOperationCompleted);
            }
            this.InvokeAsync("solicitarPresupuesto", new object[] {
                        referenciaPieza,
                        idProveedor,
                        SoapKey}, this.solicitarPresupuestoOperationCompleted, userState);
        }
        
        private void OnsolicitarPresupuestoOperationCompleted(object arg) {
            if ((this.solicitarPresupuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarPresupuestoCompleted(this, new solicitarPresupuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void validarNIFCompletedEventHandler(object sender, validarNIFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarNIFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarNIFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void validarIBANCompletedEventHandler(object sender, validarIBANCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarIBANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarIBANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void consultaCodigoPostalCompletedEventHandler(object sender, consultaCodigoPostalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCodigoPostalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCodigoPostalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string poblacion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string provincia {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void generarPresupuestoCompletedEventHandler(object sender, generarPresupuestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarPresupuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarPresupuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool presupuestoGeneradoCorrectamente {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void solicitarPresupuestoCompletedEventHandler(object sender, solicitarPresupuestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarPresupuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarPresupuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool disponibilidadPieza {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaDisponibilidadPieza {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591