//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica1Cliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/servicio/", ConfigurationName="ServiceReference1.servicio")]
    public interface servicio {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nif del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/validarNIF", ReplyAction="*")]
        practica1Cliente.ServiceReference1.validarNIFResponse validarNIF(practica1Cliente.ServiceReference1.validarNIFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/validarNIF", ReplyAction="*")]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.validarNIFResponse> validarNIFAsync(practica1Cliente.ServiceReference1.validarNIFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/validarIBAN", ReplyAction="*")]
        practica1Cliente.ServiceReference1.validarIBANResponse validarIBAN(practica1Cliente.ServiceReference1.validarIBANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/validarIBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.validarIBANResponse> validarIBANAsync(practica1Cliente.ServiceReference1.validarIBANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/consultaCodigoPostal", ReplyAction="*")]
        practica1Cliente.ServiceReference1.consultaCodigoPostalResponse consultaCodigoPostal(practica1Cliente.ServiceReference1.consultaCodigoPostalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/consultaCodigoPostal", ReplyAction="*")]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.consultaCodigoPostalResponse> consultaCodigoPostalAsync(practica1Cliente.ServiceReference1.consultaCodigoPostalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/generarPresupuesto", ReplyAction="*")]
        practica1Cliente.ServiceReference1.generarPresupuestoResponse generarPresupuesto(practica1Cliente.ServiceReference1.generarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/generarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.generarPresupuestoResponse> generarPresupuestoAsync(practica1Cliente.ServiceReference1.generarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/solicitarPresupuesto", ReplyAction="*")]
        practica1Cliente.ServiceReference1.solicitarPresupuestoResponse solicitarPresupuesto(practica1Cliente.ServiceReference1.solicitarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/servicio/solicitarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.solicitarPresupuestoResponse> solicitarPresupuestoAsync(practica1Cliente.ServiceReference1.solicitarPresupuestoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIF", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.validarNIFRequestBody Body;
        
        public validarNIFRequest() {
        }
        
        public validarNIFRequest(practica1Cliente.ServiceReference1.validarNIFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nif;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SoapKey;
        
        public validarNIFRequestBody() {
        }
        
        public validarNIFRequestBody(string nif, string SoapKey) {
            this.nif = nif;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIFResponse", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.validarNIFResponseBody Body;
        
        public validarNIFResponse() {
        }
        
        public validarNIFResponse(practica1Cliente.ServiceReference1.validarNIFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @out;
        
        public validarNIFResponseBody() {
        }
        
        public validarNIFResponseBody(bool @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBAN", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.validarIBANRequestBody Body;
        
        public validarIBANRequest() {
        }
        
        public validarIBANRequest(practica1Cliente.ServiceReference1.validarIBANRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iban;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SoapKey;
        
        public validarIBANRequestBody() {
        }
        
        public validarIBANRequestBody(string iban, string SoapKey) {
            this.iban = iban;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBANResponse", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.validarIBANResponseBody Body;
        
        public validarIBANResponse() {
        }
        
        public validarIBANResponse(practica1Cliente.ServiceReference1.validarIBANResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @out;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public validarIBANResponseBody() {
        }
        
        public validarIBANResponseBody(bool @out, string error) {
            this.@out = @out;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCodigoPostalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCodigoPostal", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.consultaCodigoPostalRequestBody Body;
        
        public consultaCodigoPostalRequest() {
        }
        
        public consultaCodigoPostalRequest(practica1Cliente.ServiceReference1.consultaCodigoPostalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaCodigoPostalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodigoPostal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SoapKey;
        
        public consultaCodigoPostalRequestBody() {
        }
        
        public consultaCodigoPostalRequestBody(string CodigoPostal, string SoapKey) {
            this.CodigoPostal = CodigoPostal;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCodigoPostalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCodigoPostalResponse", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.consultaCodigoPostalResponseBody Body;
        
        public consultaCodigoPostalResponse() {
        }
        
        public consultaCodigoPostalResponse(practica1Cliente.ServiceReference1.consultaCodigoPostalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaCodigoPostalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoPostal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string poblacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string provincia;
        
        public consultaCodigoPostalResponseBody() {
        }
        
        public consultaCodigoPostalResponseBody(string codigoPostal, string poblacion, string provincia) {
            this.codigoPostal = codigoPostal;
            this.poblacion = poblacion;
            this.provincia = provincia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarPresupuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarPresupuesto", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.generarPresupuestoRequestBody Body;
        
        public generarPresupuestoRequest() {
        }
        
        public generarPresupuestoRequest(practica1Cliente.ServiceReference1.generarPresupuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarPresupuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechaPresupuesto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string referenciaProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidadProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SoapKey;
        
        public generarPresupuestoRequestBody() {
        }
        
        public generarPresupuestoRequestBody(string fechaPresupuesto, int idCliente, string referenciaProducto, int cantidadProducto, string SoapKey) {
            this.fechaPresupuesto = fechaPresupuesto;
            this.idCliente = idCliente;
            this.referenciaProducto = referenciaProducto;
            this.cantidadProducto = cantidadProducto;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarPresupuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarPresupuestoResponse", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.generarPresupuestoResponseBody Body;
        
        public generarPresupuestoResponse() {
        }
        
        public generarPresupuestoResponse(practica1Cliente.ServiceReference1.generarPresupuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarPresupuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPresupuesto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool presupuestoGeneradoCorrectamente;
        
        public generarPresupuestoResponseBody() {
        }
        
        public generarPresupuestoResponseBody(int idPresupuesto, bool presupuestoGeneradoCorrectamente) {
            this.idPresupuesto = idPresupuesto;
            this.presupuestoGeneradoCorrectamente = presupuestoGeneradoCorrectamente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarPresupuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitarPresupuesto", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.solicitarPresupuestoRequestBody Body;
        
        public solicitarPresupuestoRequest() {
        }
        
        public solicitarPresupuestoRequest(practica1Cliente.ServiceReference1.solicitarPresupuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class solicitarPresupuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referenciaPieza;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idProveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SoapKey;
        
        public solicitarPresupuestoRequestBody() {
        }
        
        public solicitarPresupuestoRequestBody(string referenciaPieza, int idProveedor, string SoapKey) {
            this.referenciaPieza = referenciaPieza;
            this.idProveedor = idProveedor;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarPresupuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitarPresupuestoResponse", Namespace="http://www.example.org/servicio/", Order=0)]
        public practica1Cliente.ServiceReference1.solicitarPresupuestoResponseBody Body;
        
        public solicitarPresupuestoResponse() {
        }
        
        public solicitarPresupuestoResponse(practica1Cliente.ServiceReference1.solicitarPresupuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class solicitarPresupuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precioPieza;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool disponibilidadPieza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaDisponibilidadPieza;
        
        public solicitarPresupuestoResponseBody() {
        }
        
        public solicitarPresupuestoResponseBody(float precioPieza, bool disponibilidadPieza, string fechaDisponibilidadPieza) {
            this.precioPieza = precioPieza;
            this.disponibilidadPieza = disponibilidadPieza;
            this.fechaDisponibilidadPieza = fechaDisponibilidadPieza;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioChannel : practica1Cliente.ServiceReference1.servicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioClient : System.ServiceModel.ClientBase<practica1Cliente.ServiceReference1.servicio>, practica1Cliente.ServiceReference1.servicio {
        
        public servicioClient() {
        }
        
        public servicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        practica1Cliente.ServiceReference1.validarNIFResponse practica1Cliente.ServiceReference1.servicio.validarNIF(practica1Cliente.ServiceReference1.validarNIFRequest request) {
            return base.Channel.validarNIF(request);
        }
        
        public bool validarNIF(string nif, string SoapKey) {
            practica1Cliente.ServiceReference1.validarNIFRequest inValue = new practica1Cliente.ServiceReference1.validarNIFRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.validarNIFRequestBody();
            inValue.Body.nif = nif;
            inValue.Body.SoapKey = SoapKey;
            practica1Cliente.ServiceReference1.validarNIFResponse retVal = ((practica1Cliente.ServiceReference1.servicio)(this)).validarNIF(inValue);
            return retVal.Body.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.validarNIFResponse> practica1Cliente.ServiceReference1.servicio.validarNIFAsync(practica1Cliente.ServiceReference1.validarNIFRequest request) {
            return base.Channel.validarNIFAsync(request);
        }
        
        public System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.validarNIFResponse> validarNIFAsync(string nif, string SoapKey) {
            practica1Cliente.ServiceReference1.validarNIFRequest inValue = new practica1Cliente.ServiceReference1.validarNIFRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.validarNIFRequestBody();
            inValue.Body.nif = nif;
            inValue.Body.SoapKey = SoapKey;
            return ((practica1Cliente.ServiceReference1.servicio)(this)).validarNIFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        practica1Cliente.ServiceReference1.validarIBANResponse practica1Cliente.ServiceReference1.servicio.validarIBAN(practica1Cliente.ServiceReference1.validarIBANRequest request) {
            return base.Channel.validarIBAN(request);
        }
        
        public bool validarIBAN(string iban, string SoapKey, out string error) {
            practica1Cliente.ServiceReference1.validarIBANRequest inValue = new practica1Cliente.ServiceReference1.validarIBANRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.validarIBANRequestBody();
            inValue.Body.iban = iban;
            inValue.Body.SoapKey = SoapKey;
            practica1Cliente.ServiceReference1.validarIBANResponse retVal = ((practica1Cliente.ServiceReference1.servicio)(this)).validarIBAN(inValue);
            error = retVal.Body.error;
            return retVal.Body.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.validarIBANResponse> practica1Cliente.ServiceReference1.servicio.validarIBANAsync(practica1Cliente.ServiceReference1.validarIBANRequest request) {
            return base.Channel.validarIBANAsync(request);
        }
        
        public System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.validarIBANResponse> validarIBANAsync(string iban, string SoapKey) {
            practica1Cliente.ServiceReference1.validarIBANRequest inValue = new practica1Cliente.ServiceReference1.validarIBANRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.validarIBANRequestBody();
            inValue.Body.iban = iban;
            inValue.Body.SoapKey = SoapKey;
            return ((practica1Cliente.ServiceReference1.servicio)(this)).validarIBANAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        practica1Cliente.ServiceReference1.consultaCodigoPostalResponse practica1Cliente.ServiceReference1.servicio.consultaCodigoPostal(practica1Cliente.ServiceReference1.consultaCodigoPostalRequest request) {
            return base.Channel.consultaCodigoPostal(request);
        }
        
        public string consultaCodigoPostal(string CodigoPostal, string SoapKey, out string poblacion, out string provincia) {
            practica1Cliente.ServiceReference1.consultaCodigoPostalRequest inValue = new practica1Cliente.ServiceReference1.consultaCodigoPostalRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.consultaCodigoPostalRequestBody();
            inValue.Body.CodigoPostal = CodigoPostal;
            inValue.Body.SoapKey = SoapKey;
            practica1Cliente.ServiceReference1.consultaCodigoPostalResponse retVal = ((practica1Cliente.ServiceReference1.servicio)(this)).consultaCodigoPostal(inValue);
            poblacion = retVal.Body.poblacion;
            provincia = retVal.Body.provincia;
            return retVal.Body.codigoPostal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.consultaCodigoPostalResponse> practica1Cliente.ServiceReference1.servicio.consultaCodigoPostalAsync(practica1Cliente.ServiceReference1.consultaCodigoPostalRequest request) {
            return base.Channel.consultaCodigoPostalAsync(request);
        }
        
        public System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.consultaCodigoPostalResponse> consultaCodigoPostalAsync(string CodigoPostal, string SoapKey) {
            practica1Cliente.ServiceReference1.consultaCodigoPostalRequest inValue = new practica1Cliente.ServiceReference1.consultaCodigoPostalRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.consultaCodigoPostalRequestBody();
            inValue.Body.CodigoPostal = CodigoPostal;
            inValue.Body.SoapKey = SoapKey;
            return ((practica1Cliente.ServiceReference1.servicio)(this)).consultaCodigoPostalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        practica1Cliente.ServiceReference1.generarPresupuestoResponse practica1Cliente.ServiceReference1.servicio.generarPresupuesto(practica1Cliente.ServiceReference1.generarPresupuestoRequest request) {
            return base.Channel.generarPresupuesto(request);
        }
        
        public int generarPresupuesto(string fechaPresupuesto, int idCliente, string referenciaProducto, int cantidadProducto, string SoapKey, out bool presupuestoGeneradoCorrectamente) {
            practica1Cliente.ServiceReference1.generarPresupuestoRequest inValue = new practica1Cliente.ServiceReference1.generarPresupuestoRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.generarPresupuestoRequestBody();
            inValue.Body.fechaPresupuesto = fechaPresupuesto;
            inValue.Body.idCliente = idCliente;
            inValue.Body.referenciaProducto = referenciaProducto;
            inValue.Body.cantidadProducto = cantidadProducto;
            inValue.Body.SoapKey = SoapKey;
            practica1Cliente.ServiceReference1.generarPresupuestoResponse retVal = ((practica1Cliente.ServiceReference1.servicio)(this)).generarPresupuesto(inValue);
            presupuestoGeneradoCorrectamente = retVal.Body.presupuestoGeneradoCorrectamente;
            return retVal.Body.idPresupuesto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.generarPresupuestoResponse> practica1Cliente.ServiceReference1.servicio.generarPresupuestoAsync(practica1Cliente.ServiceReference1.generarPresupuestoRequest request) {
            return base.Channel.generarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.generarPresupuestoResponse> generarPresupuestoAsync(string fechaPresupuesto, int idCliente, string referenciaProducto, int cantidadProducto, string SoapKey) {
            practica1Cliente.ServiceReference1.generarPresupuestoRequest inValue = new practica1Cliente.ServiceReference1.generarPresupuestoRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.generarPresupuestoRequestBody();
            inValue.Body.fechaPresupuesto = fechaPresupuesto;
            inValue.Body.idCliente = idCliente;
            inValue.Body.referenciaProducto = referenciaProducto;
            inValue.Body.cantidadProducto = cantidadProducto;
            inValue.Body.SoapKey = SoapKey;
            return ((practica1Cliente.ServiceReference1.servicio)(this)).generarPresupuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        practica1Cliente.ServiceReference1.solicitarPresupuestoResponse practica1Cliente.ServiceReference1.servicio.solicitarPresupuesto(practica1Cliente.ServiceReference1.solicitarPresupuestoRequest request) {
            return base.Channel.solicitarPresupuesto(request);
        }
        
        public float solicitarPresupuesto(string referenciaPieza, int idProveedor, string SoapKey, out bool disponibilidadPieza, out string fechaDisponibilidadPieza) {
            practica1Cliente.ServiceReference1.solicitarPresupuestoRequest inValue = new practica1Cliente.ServiceReference1.solicitarPresupuestoRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.solicitarPresupuestoRequestBody();
            inValue.Body.referenciaPieza = referenciaPieza;
            inValue.Body.idProveedor = idProveedor;
            inValue.Body.SoapKey = SoapKey;
            practica1Cliente.ServiceReference1.solicitarPresupuestoResponse retVal = ((practica1Cliente.ServiceReference1.servicio)(this)).solicitarPresupuesto(inValue);
            disponibilidadPieza = retVal.Body.disponibilidadPieza;
            fechaDisponibilidadPieza = retVal.Body.fechaDisponibilidadPieza;
            return retVal.Body.precioPieza;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.solicitarPresupuestoResponse> practica1Cliente.ServiceReference1.servicio.solicitarPresupuestoAsync(practica1Cliente.ServiceReference1.solicitarPresupuestoRequest request) {
            return base.Channel.solicitarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<practica1Cliente.ServiceReference1.solicitarPresupuestoResponse> solicitarPresupuestoAsync(string referenciaPieza, int idProveedor, string SoapKey) {
            practica1Cliente.ServiceReference1.solicitarPresupuestoRequest inValue = new practica1Cliente.ServiceReference1.solicitarPresupuestoRequest();
            inValue.Body = new practica1Cliente.ServiceReference1.solicitarPresupuestoRequestBody();
            inValue.Body.referenciaPieza = referenciaPieza;
            inValue.Body.idProveedor = idProveedor;
            inValue.Body.SoapKey = SoapKey;
            return ((practica1Cliente.ServiceReference1.servicio)(this)).solicitarPresupuestoAsync(inValue);
        }
    }
}
